DEBUG = "True"

TEMPLATES_DIR = "templates"
GLOBAL_TEMPLATES_DIR = "global_templates"

LOGGING = "True"
LOGGER_STDOUT = "console"
LOG_FILE = "mylog"
LOG_FILE_DIR = "logging"

DEFAULT_LOGGER = "True"
DEFAULT_LOGGER_EXCLUDE = []

SITE_ADR = "127.0.0.1"
SITE_PORT = 8000

DEFAULT_AUTHORIZATION = "True"

MIDDLEWARE = [
    "wsgi_framework.middleware.print_environ",
    "wsgi_framework.middleware.default_authentication",
    "middleware.custom_middleware.my_custom_middleware"
]