DEBUG = "True"

TEMPLATES_DIR = "templates"
GLOBAL_TEMPLATES_DIR = "global_templates"

LOGGING = "True"
LOGGER_STDOUT = "console"
LOG_FILE = "mylog"
LOG_FILE_DIR = "logging"

DEFAULT_LOGGER = "False"
DEFAULT_LOGGER_EXCLUDE = ["Debug"]
#DEFAULT_LOGGER_EXCLUDE = []

SITE_ADR = "127.0.0.1"
SITE_PORT = 8000